baseurl = "https://dotstud.io"
title = ".studio（ドットスタジオ）"
canonifyurls = true
paginate = 10
theme = "dotstudio"
languageCode = "ja"
copyright = "© 2016 Team DevRel, LIG Inc."

[author]
  name = "ドットスタジオ"

[params]
  # DateForm = "Mon, Jan 2, 2006"
  DateForm = "2006.01.02"
  Description = "ドットスタジオはIoTのセレクトショップです。実際のユースケースとなるブログ記事を中心に、海外の面白いIoTデバイスやハードウェア、開発者向けのパーツなどを紹介していきます。"
  Author = "dotstudio Inc."
  email = "info@dotstud.io"
  Ganalytics = "UA-78080011-1"

[[params.social]]
  title = "twitter"
  url = "https://twitter.com/humboldtux"
[[params.social]]
  title = "github"
  url = "https://github.com/humboldtux"
[[params.social]]
  title = "facebook"
  url = "https://www.facebook.com/FACEBOOKHANDLE"

[[menu.main]]
  name = "PROJECTS"
  url = "/"
  identifier = "projects"
  weight = -200
# [[menu.main]]
#   name = "EVENTS"
#   url = "/events/"
#   identifier = "events"
#   weight = -180
[[menu.main]]
  name = "BLOG"
  url = "/blog/"
  identifier = "blog"
  weight = -180

[taxonomies]
tag = "tags"
category = "categories"
